module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#051f1e",
        "on-primary-container": "#8cade7",
        "tertiary": "#1b3000",
        "surface-dim": "#c4dfdd",
        "surface-container": "#d8f3f1",
        "primary-container": "#1b4073",
        "inverse-surface": "#1c3533",
        "surface-container-highest": "#cde8e6",
        "surface-tint": "#3d5f93",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#001f2a",
        "surface-container-low": "#ddf9f7",
        "primary": "#1B4073",
        "inverse-primary": "#a9c7ff",
        "on-surface-variant": "#43474f",
        "tertiary-fixed": "#8CC540",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#d6e3ff",
        "surface-bright": "#e3fffc",
        "on-tertiary-container": "#102000",
        "secondary": "#006684",
        "secondary-container": "#86daff",
        "on-tertiary-fixed": "#ffffff",
        "background": "#f8fafc",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#7cd1f7",
        "outline-variant": "#c3c6d1",
        "on-primary-fixed": "#001b3d",
        "surface-container-high": "#d2eeeb",
        "inverse-on-surface": "#dbf6f4",
        "outline": "#747780",
        "surface": "#f8fafc",
        "on-error-container": "#93000a",
        "on-primary-fixed-variant": "#23477a",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#9dd851",
        "secondary-fixed": "#bde9ff",
        "on-secondary-container": "#005f7b",
        "on-tertiary-fixed-variant": "#304f00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#2b4800",
        "on-secondary-fixed-variant": "#004d64",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "surface-variant": "#cde8e6",
        "on-background": "#051f1e",
        "primary-fixed-dim": "#a9c7ff",
        "lime-brand": "#8CC540",
        "navy-brand": "#1B4073",
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
